# Generated by Django 4.2.7 on 2023-11-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_patient_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='age',
            field=models.IntegerField(null=True),
        ),
    ]
