# Generated by Django 4.2.7 on 2023-11-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='on_hold',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='quantity',
            field=models.FloatField(default=0),
        ),
    ]
