# Generated by Django 4.2.7 on 2023-11-27 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_patient_age'),
        ('recordsapp', '0002_vaccine_on_hold_vaccine_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccinationrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientvaccinations', to='users.patient'),
        ),
    ]
