# Generated by Django 4.2.7 on 2023-11-28 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_alter_nurseschedule_nurse'),
        ('recordsapp', '0003_alter_vaccinationrecord_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationrecord',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vaccinationrecord',
            name='vaccine_schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.vaccineschedule'),
        ),
    ]
