# Generated by Django 4.2.7 on 2023-11-27 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordsapp', '0002_vaccine_on_hold_vaccine_quantity'),
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccineschedule',
            name='vaccine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recordsapp.vaccine'),
        ),
    ]
