# Generated by Django 4.2.7 on 2023-11-27 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_patient_age'),
        ('appointments', '0003_remove_appointment_nurse_remove_appointment_vaccine'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='nurse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.nurse'),
        ),
    ]
