# Generated by Django 4.2.7 on 2023-11-27 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_vaccineschedule_available_slots_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccineschedule',
            old_name='sesstion_date',
            new_name='session_date',
        ),
    ]
