# Generated by Django 4.2.7 on 2023-11-27 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_patient_age'),
        ('appointments', '0006_rename_sesstion_date_vaccineschedule_session_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='nurse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurseappointments', to='users.nurse'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patientappointments', to='users.patient'),
        ),
    ]
