# Generated by Django 4.2.7 on 2023-11-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointment_nurse_alter_appointment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='accepted',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
