# Generated by Django 4.2.7 on 2023-11-28 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_patient_age'),
        ('appointments', '0008_alter_appointment_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='NurseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.nurse')),
                ('vaccine_schedule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.vaccineschedule')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
