# Generated by Django 4.2.7 on 2023-11-28 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_patient_age'),
        ('appointments', '0010_nurseschedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurseschedule',
            name='nurse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurseschedules', to='users.nurse'),
        ),
    ]
